! PROJECT EULER
! PROBLEM 2
! Each new term in the Fibonacci sequence is generated by adding the previous
!  two terms. By starting with 1 and 2, the first 10 terms will be:
!  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
! By considering the terms in the Fibonacci sequence whose values do not exceed
!  four million, find the sum of the even-valued terms.


program PE2
!  implicit none
  integer :: sum, a, b
  integer, dimension(1:45) :: fibs   ! first 45 fib numbers

  write(*,*) ''
  write(*,*) 'PE2'
  write(*,*) 'By considering the terms in the Fibonacci sequence whose values'
  write(*,*) ' do not exceed four million, find the sum of the even-valued terms.'

  ! Declare initial Fibonacci values
  fibs(1) = 1
  fibs(2) = 2

  ! find the first 40 Fibonacci values
  do i = 1, 43
    fibs(i+2) = fibs(i) + fibs(i+1)   ! sum of previous fibs values
  end do

  ! pick out each third Fibonacci number
  do i = 0, 45/3-1, 1

    ! Fibonacci values beyond 4 mil exit program
    if (fibs(2+3*i) .ge. 4000000) then
      exit
    end if

    ! If less than 4 mil, add to the sum
    sum = sum + fibs(2+i*3)
  end do

  write(*,*) 'Ans = ', sum
  write(*,*) ''

end program PE2
