%{ 
   Project Euler problem 29 - Distinct Powers

    Consider all integer combinations of a^b for 2 ? a ? 5 and 2 ? b ? 5:

    2^2=4, 2^3=8, 2^4=16, 2^5=32
    3^2=9, 3^3=27, 3^4=81, 3^5=243
    4^2=16, 4^3=64, 4^4=256, 4^5=1024
    5^2=25, 5^3=125, 5^4=625, 5^5=3125

    If they are then placed in numerical order, with any repeats removed,
     we get the following sequence of 15 distinct terms:

    4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

    How many distinct terms are in the sequence generated by a^b for
     2 ? a ? 100 and 2 ? b ? 100?
%}

format long g
tic

% intialize a zeros sequence for storing a^b, i indexes the sequence
seq = zeros(10000,1);
i = 1;

% calculate each a^b and check if it can be found in 'seq' array already
%  if not, store it and increment the index 'i', otherwise just move on
for a = 2:100
    for b = 2:100
        if(~ismember(a^b, seq))
            seq(i,1) = a^b;
            i = i + 1;
        end
    end
end

% remove all remnant zeros from seq
seq(seq == 0) = [];

% print answer and elapsed time
fprintf('Total number of distinct values = %d. \n', length(seq))
toc

