%
% Project Euler 2 - Fibonnaci sequence sum
%
% Each new term in the Fibonacci sequence is generated by adding the
%  previous two terms. By starting with 1 and 2, the first 10 terms will be:
% 
%    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% 
% By considering the terms in the Fibonacci sequence whose values do not
%  exceed four million, find the sum of the even-valued terms.
% 


% initialize fibonacci sequence with two temp values
temp1 = 1;
temp2 = 2;

% initialize summation with the first even-valued fibonnaci number
sum = temp2;

% cycle thru first 100 fibonnaci numbers
for i = 1:100
    % calculate new fib number
    fib = temp1 + temp2;
    
    % if fib is even, add to sum
    if(mod(fib,2) == 0)
        sum = sum + fib;
    end
    
    % save next two fib numbers
    temp1 = temp2;
    temp2 = fib;
    
    % leave if fib greater than 4 mil
    if(fib > 4e6)
        break
    end
end

disp(sum)
