%
% Project Euler 12 - Highly divisible triangular number
% 
% The sequence of triangle numbers is generated by adding the natural
%  numbers. So the 7th triangle number would be
%     1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
% 
% The first ten terms would be:
%     1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
%
% Let us list the factors of the first seven triangle numbers:
%
%  1: 1
%  3: 1,3
%  6: 1,2,3,6
% 10: 1,2,5,10
% 15: 1,3,5,15
% 21: 1,3,7,21
% 28: 1,2,4,7,14,28
% We can see that 28 is the first triangle number to have over five
%  divisors.
%
% What is the value of the first triangle number to have over 
%  five hundred divisors?
% 

% define highest triangle number and target number of divisors
max_tri_num = 2e4;
n_divisors = 500;
tic

% calculate triangle term i
for i = 1:max_tri_num
    
    % calculate triangle num as 'triangle_num'
    triangle_term = 0;
    for j = 1:i
      triangle_term = triangle_term + j;
    end
    
    % determine the number of factors in current triangle term
    divisors_per_term = 0;
    for k = 1:ceil(sqrt(triangle_term))
        if(mod(triangle_term,k) == 0)
            divisors_per_term = divisors_per_term + 2;
        elseif(k*k == triangle_term)
            divisors_per_term = divisors_per_term - 1;
        end
    end
    
    % print answer and elapsed time
    if(divisors_per_term > n_divisors)
        triangle_term
        divisors_per_term
        toc
        break
    end
    
end

