%{
   Project Euler problem 44 - Pentagon numbers

    Pentagonal numbers are generated by the formula, Pn=n(3n?1)/2. 
     The first ten pentagonal numbers are:

    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

    It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their
     difference, 70 ? 22 = 48, is not pentagonal.

    Find the pair of pentagonal numbers, Pj and Pk, for which their 
     sum and difference are pentagonal and D = |Pk ? Pj| is minimised; 
     what is the value of D?
%}

% initizialize some variables
tic
notFound = 1;
j = 2;

while(notFound == 1)
    j = j + 1;
    n = j*(3*j - 1)/2;
 
    for k = j-1:-1:1
        m = k*(3*k - 1)/2;
        if(is_pentagonal(n - m)==0 && is_pentagonal(n + m)==0)
            D = abs(n - m);
            notFound = 0;
            fprintf('\nj = %d // k = %d // D = %d\n', j,k,D)
            toc
            break;
        end
    end
end



% determine if n is pentagonal
function TF = is_pentagonal(n)
    temp = (sqrt(1 + 24*n) + 1)/6;
    TF = mod(temp,1);
end






