"""
Project Euler 2
Fibonnaci sequence sum

Each new term in the Fibonacci sequence is generated by adding the previous two
 terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

import numpy as np

print('By considering the terms in the Fibonacci sequence whose values do not',
      'exceed four million, find the sum of the even-valued terms.')

sum = 0
fib = [1, 2]

for f in np.arange(2, 50):
    new_fib = fib[f-1] + fib[f-2]
    
    if(new_fib > 4e6):
        break
    else:
        fib.append(new_fib)
    
for f in fib:
    if(f % 2 == 0):
        sum = sum + f

print('sum =', sum)

    