%{ 
   Project Euler problem 44 - Pentagon numbers

    Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
     The first ten pentagonal numbers are:

    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

    It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their 
     difference, 70 − 22 = 48, is not pentagonal.

    Find the pair of pentagonal numbers, Pj and Pk, for which their sum 
     and difference are pentagonal and D = |Pk − Pj| is minimised; what 
     is the value of D?
%}

% initialize some variables
tic
N = 3000;
Pn = zeros(1,N);
D_min = 0;

% fill pentagonal numbers array, Pn(1:N)
for n = 1:N
    Pn(1,n) = n*(3*n-1)/2;
end

% test each pentagonal number i=1:N with another pentagonal number j=i:N
for i = 1:N
    pent_1 = Pn(i);
    for j = i:N
        pent_2 = Pn(j);
        
        % solve for difference
        D = abs(pent_2 - pent_1);
        
        % test if sum and difference are pentagonal
        if(is_pentagonal(pent_1+pent_2)== 1 && is_pentagonal(D) == 1)
            D_min = D; % store if it is (only one so no minimum check)
        end
    end
end

% print answer
fprintf('Lowest D = %d.\n', D_min)
toc

% solved inverse function to determine if a number is pentagonal
% test must be a natural number for n input to be a pentagonal number.
function tf = is_pentagonal(n)
    test = (sqrt(24*n + 1) + 1)/6;
    if(rem(test,1) == 0)
        tf = 1;
    else
        tf = 0;
    end
end
